export { default as playIcon } from './images/play.svg'
export { default as starIcon } from './images/star.png'
export { default as heartIcon } from './images/heart.png'
export { default as searchIcon } from './images/search.svg'
export { default as filterIcon } from './images/filter.svg'
export { default as bannerImg } from './images/banner.png'
export { default as notFoundImg } from './images/404.png'

// streaming logos
export { default as amazonIcon } from './images/streamingLogos/amazon.svg'
export { default as crunchyrollIcon } from './images/streamingLogos/crunchyroll.svg'
export { default as funimationIcon } from './images/streamingLogos/funimation.svg'
export { default as huluIcon } from './images/streamingLogos/hulu.svg'
export { default as tubiIcon } from './images/streamingLogos/tubi.svg'
export { default as netflixIcon } from './images/streamingLogos/netflix.svg'
export { default as globeIcon } from './images/streamingLogos/globe.svg'